import { jsPDF } from 'jspdf'

const MARGIN = 48
const PAGE_W = 595.28 // A4 width in pt
const PAGE_H = 841.89 // A4 height in pt
const CONTENT_W = PAGE_W - MARGIN * 2

/**
 * Generates a multi-page PDF checklist/summary for a roadmap and triggers
 * a browser download. Pure client-side — no server round-trip.
 */
export function downloadRoadmapPdf(roadmap, { isTopicComplete } = {}) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  let y = MARGIN

  const newPageIfNeeded = (needed) => {
    if (y + needed > PAGE_H - MARGIN) {
      doc.addPage()
      y = MARGIN
    }
  }

  const heading = (text, size = 18) => {
    newPageIfNeeded(size + 14)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(size)
    doc.setTextColor(20, 20, 30)
    doc.text(text, MARGIN, y)
    y += size + 10
  }

  const subheading = (text) => {
    newPageIfNeeded(24)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12.5)
    doc.setTextColor(90, 40, 200)
    doc.text(text, MARGIN, y)
    y += 18
  }

  const paragraph = (text, size = 10.5, color = [70, 70, 80]) => {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(size)
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, CONTENT_W)
    lines.forEach((line) => {
      newPageIfNeeded(size + 4)
      doc.text(line, MARGIN, y)
      y += size + 4
    })
  }

  const bullet = (text, checked) => {
    const size = 10.5
    const lines = doc.splitTextToSize(text, CONTENT_W - 22)
    newPageIfNeeded(size + 4 + (lines.length - 1) * (size + 2))

    // checkbox
    doc.setDrawColor(140, 140, 160)
    doc.roundedRect(MARGIN, y - size + 2, 10, 10, 2, 2)
    if (checked) {
      doc.setDrawColor(90, 40, 200)
      doc.setLineWidth(1.3)
      doc.line(MARGIN + 2, y - 4, MARGIN + 4.5, y - 1)
      doc.line(MARGIN + 4.5, y - 1, MARGIN + 8.5, y - 7)
      doc.setLineWidth(1)
    }

    doc.setFont('helvetica', checked ? 'normal' : 'normal')
    doc.setFontSize(size)
    doc.setTextColor(checked ? 150 : 50, checked ? 150 : 50, checked ? 160 : 60)
    lines.forEach((line, i) => {
      doc.text(line, MARGIN + 18, y + i * (size + 2))
    })
    y += lines.length * (size + 2) + 4
  }

  const divider = () => {
    newPageIfNeeded(14)
    doc.setDrawColor(225, 225, 235)
    doc.line(MARGIN, y, PAGE_W - MARGIN, y)
    y += 16
  }

  // ---- Title block ----
  doc.setFillColor(124, 58, 237)
  doc.rect(0, 0, PAGE_W, 6, 'F')
  y = MARGIN + 10

  heading(roadmap.title, 22)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(120, 120, 130)
  doc.text(`${roadmap.category} · ${roadmap.duration}`, MARGIN, y)
  y += 22

  paragraph(roadmap.description)
  y += 6

  // Salary table
  subheading('Salary Overview')
  const salaryRows = [
    ['Entry Level', roadmap.salary.entry],
    ['Mid Level', roadmap.salary.mid],
    ['Senior Level', roadmap.salary.senior],
  ]
  salaryRows.forEach(([label, val]) => {
    newPageIfNeeded(16)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10.5)
    doc.setTextColor(70, 70, 80)
    doc.text(label, MARGIN, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(20, 130, 130)
    doc.text(val, MARGIN + 140, y)
    y += 16
  })
  y += 8

  // Skills
  subheading('Core Skills')
  paragraph(roadmap.skills.join('   •   '))
  y += 6
  divider()

  // Learning roadmap with checklist
  heading('Learning Roadmap', 15)
  roadmap.levels.forEach((level) => {
    newPageIfNeeded(20)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(30, 30, 40)
    doc.text(`${level.level}  (${level.duration})`, MARGIN, y)
    y += 16

    level.topics.forEach((topic) => {
      const done = isTopicComplete ? isTopicComplete(roadmap.id, topic.id) : false
      bullet(`${topic.title} — ${topic.description}`, done)
    })
    y += 6
  })

  divider()

  // Resources
  subheading('Learning Resources')
  roadmap.resources.forEach((r) => paragraph(`• ${r.title}  (${r.type})`))
  y += 8

  // Projects
  subheading('Project Recommendations')
  roadmap.projects.forEach((p) => paragraph(`• ${p.title}  (${p.difficulty})`))
  y += 8

  // Certificates
  subheading('Certificates to Pursue')
  roadmap.certificates.forEach((c) => paragraph(`• ${c.name} — ${c.provider}`))

  // Footer on every page
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(160, 160, 170)
    doc.text('Generated by RoadmapX', MARGIN, PAGE_H - 24)
    doc.text(`Page ${i} of ${pageCount}`, PAGE_W - MARGIN - 60, PAGE_H - 24)
  }

  const filename = `${roadmap.id}-roadmap.pdf`
  doc.save(filename)
}
